### ISSUE TITLE
Allow to change the scroll context in RespondsToScroll mixin

### ISSUE THREAD

**Issue by eduardoweiland** [dollarshaveclub/ember-responds-to#13]
Currently this mixin always bind to the scroll event on the window object. This way, it cannot be used on other components that have `overflow: auto` (in my case, it's a dropdown menu).

**Comment by YoranBrondsema** [comment]
Do you have multiple components that need to listen to the scroll events on the same element? If not, a mixin is probably overkill and something like [ember-lifeline](https://github.com/rwjblue/ember-lifeline#addeventlistener) could provide a solution.

If you, I think the best would be for you to implement your own mixin based on the current implementation of [responds-to-scroll.js](https://github.com/dollarshaveclub/ember-responds-to/blob/master/addon/mixins/responds-to-resize.js). I think your case would involve some communication between the mixin and the object using it (to pass around the element on which to listen for events) and I can't really think of a clean way of achieving this that doesn't involve some "magic" parameters.

I'm definitely open to your suggestions though!

**Comment by eduardoweiland** [comment]
I am already using my own mixin like this:

```diff
 import Ember from 'ember';
 import DebouncedResponse from './debounced-response';
 
 const RESIZE_EVENTS = 'resize orientationchange';
 function noop() { }
 
 // Debounces browser event, triggers 'resize' event and calls 'resize' handler.
 export default Ember.Mixin.create(
   Ember.Evented,
   DebouncedResponse,
   {
 
     resize: noop,
 
+    scrollContext: Ember.computed(function() {
+      return Ember.$(window);
+    }),
+
     didInsertElement() {
       this._super(...arguments);
 
       this.resizeHandler = this.debounce((...args) => {
         this.trigger('resize', ...args);
         this.resize(...args);
       });
 
-      Ember.$(window).on(RESIZE_EVENTS, this.resizeHandler);
+      this.get('scrollContext').on(RESIZE_EVENTS, this.resizeHandler);
     },
 
     willDestroyElement() {
       this._super(...arguments);
 
-      Ember.$(window).on(RESIZE_EVENTS, this.resizeHandler);
+      this.get('scrollContext').on(RESIZE_EVENTS, this.resizeHandler);
     },
 
 });
```

In the components that I need to change the scrollContext using RespondsToScrollMixin, I just override `scrollContext` property:

```js
import Ember from 'ember';
import RespondsToScroll from '../mixins/responds-to-scroll';

export default Ember.Component.extend(RespondsToScroll, {
  scrollContext: Ember.computed(function() {
    return this.$();
  })

  // ...
```

**Comment by YoranBrondsema** [comment]
Yup, that's cool! I'll close it for now as I don't think there's enough reason to have such a `scrollContext` property in the addon as it can have unintended side-effects: what if a mixin from another addon also uses a property `scrollContext`? What if the component defines an unrelated property `scrollContext`?

I think it's best to treat this case in the app itself like you did, instead of at the addon level.

Thanks for sharing the code! I'm sure that will be useful for the next person trying to solve the same problem :-).
