### ISSUE TITLE
Remove jQuery

### ISSUE THREAD

**Issue by RobbieTheWagner** [dollarshaveclub/ember-responds-to#16]
It would be nice to remove the need for jQuery in this addon. Any thoughts on whether or not you would like to pursue that? If so, I may have time to do a PR at some point.

**Comment by YoranBrondsema** [comment]
The usage of jQuery is pretty basic, i.e. only listening to DOM events, so I don't see why we wouldn't want to replace it with the native DOM API. I'm all for it!

**Comment by RobbieTheWagner** [comment]
@YoranBrondsema I put up a PR to get things up to date first, and will do another one to remove jQuery, once that is merged 😄

**Comment by RobbieTheWagner** [comment]
https://github.com/dollarshaveclub/ember-responds-to/pull/17

**Comment by RobbieTheWagner** [comment]
@YoranBrondsema this should be done now. Should we release a new version?

**Comment by YoranBrondsema** [comment]
@rwwagner90 Agree.

**Comment by RobbieTheWagner** [comment]
@YoranBrondsema @briangonzalez  I don't think I have publish rights on npm, but if I could get those, I would be happy to put out 1.5.0 😄

**Comment by RobbieTheWagner** [comment]
@YoranBrondsema would you mind getting me npm permissions, so I can publish a new version?

**Comment by YoranBrondsema** [comment]
Ah sorry, I don't have them either. Maybe @briangonzalez can help us again :-)?

**Comment by briangonzalez** [comment]
Whoops, sorry fellas. Here it comes.

**Comment by briangonzalez** [comment]
@YoranBrondsema @rwwagner90 Can ya'll give me your NPM usernames?

**Comment by briangonzalez** [comment]
@YoranBrondsema Found you, now just need Robert's.

**Comment by RobbieTheWagner** [comment]
1.5.0 was released, so this is resolved 🎉

**Comment by YoranBrondsema** [comment]
@rwwagner90 Thanks for all your work in modernizing the addon!

**Comment by briangonzalez** [comment]
Yes, thanks @rwwagner90 _and_ @YoranBrondsema :)

**Comment by RobbieTheWagner** [comment]
You're welcome! Glad I could help 😄
