### ISSUE TITLE
Polyfill for window.requestAnimationFrame for Phantom.js

### ISSUE THREAD

**Issue by YoranBrondsema** [dollarshaveclub/ember-responds-to#4]
Phantom.js does not support `window.requestAnimationFrame` so a polyfill is needed when testing an app that uses some of the mixins (amongst others `RespondsToScroll`) in CI.

In my app I successfully used the polyfill from Paul Irish (https://gist.githubusercontent.com/paulirish/1579671/raw/682e5c880c92b445650c4880a6bf9f3897ec1c5b/rAF.js). My question is whether the polyfill should directly be inlcuded in `ember-responds-to`. If you think it belongs here I'd be happy to create a PR for that.

**Comment by briangonzalez** [comment]
Thanks for digging in here, Yoran. I don't think including the polyfill with the addon is the best approach, as many apps polyfill this functionality on their own anyway. 

A PR noting that the polyfill is needed during test in the README would be welcomed, though.

**Comment by briangonzalez** [comment]
Thanks Yoran!
